### ISSUE TITLE
Recharts breaking our build

### ISSUE THREAD

**Issue by OlivierCo** [recharts/react-smooth#10]
We currently use recharts in our project and after the lastest update of react-smooth, our build is breaking with the following error:

```
index.js:1Uncaught SyntaxError: Unexpected token import
...
import Animate from './Animate';
```

in react-smooth/lib/index.js

could you please have a look and release a patch.

thanks.

**Comment by tomericco** [comment]
I'm facing this issue too, by using 'recharts'.

**Comment by albertkim** [comment]
Same deal here at the moment.

**Comment by kunall17** [comment]
Any temporary fix anyone can suggest?

**Comment by duro** [comment]
We are also experiencing this

**Comment by duro** [comment]
@kunall17 I was able to work around by hard pinning react-smooth to the previous version in my package.json

Added this to my local project package.json:

```
    "react-smooth": "0.1.15",
```

**Comment by tuler** [comment]
That workaround didn't work for us.

**Comment by OlivierCo** [comment]
my solution for now has been to add react-smooth in my dependencies and use 0.1.17 for now, once this bug will be fix I will update recharts and then remove react-smooth from my direct dependencies

**Comment by mehdivk** [comment]
As @OlivierCo mentioned adding `"react-smooth": "0.1.17"` will fix the issue.

**IMPORTANT:**
`npm i react-smooth@0.1.17 --save` won't fix the problem as it adds `"react-smooth": "^0.1.17"` and the `^` allows NPM to install problematic `0.1.18`

**Comment by xile611** [comment]
Sorry! It's my fault. I forgot to check the compiled files in `/lib`. I think it has been fixed in the version 0.1.19. Please check.

**Comment by mehdivk** [comment]
@xile611 to confirm `0.1.19` fixes the problem! Thanks for the fix. It's much appreciated 👍

**Comment by xile611** [comment]
@mehdivk OK! Thanks!
