### ISSUE TITLE
Failed to resolve entry for package "react-smooth". The package may have incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by gulam-quinn** [recharts/react-smooth#103]
Getting this when running build in aws codepipeline

**Comment by ckifer** [comment]
should be fixed in 4.0.3

Sorry

**Comment by gulam-quinn** [comment]
Yes, we were using recharts, had to rollback recharts version to 2.13.3. working fine now, thanks for the update.

**Comment by ckifer** [comment]
4.0.2 of react smooth is a bad version. Not intentional 😓

Next npm update should go to 4.0.3 and avoid the issue

**Comment by ckifer** [comment]
updating to the latest should be safe now :). Hope your day goes better!
