### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by gvillo** [recharts/react-smooth#106]
Hi! it would be really cool if you would allow react 19 in package.json, since it's stable and launched now. I am using Mantine and this is one of the deps that it's raising a warning because of peerDeps

**Comment by severinlandolt** [comment]
+1. Last piece to fit in to ship Tremors v4 beta ✨
![CleanShot 2024-12-13 at 17 51 23@2x](https://github.com/user-attachments/assets/e1e9c600-8cc5-4c4c-8fba-2d4a25a1ad5f)

**Comment by aqeelat** [comment]
@ckifer the 4.0.4 release says it adds react 19 peer deps but I think that commit didn't make it into the release

**Comment by ckifer** [comment]
What makes you think that

**Comment by aqeelat** [comment]
@ckifer I was looking at the diff https://github.com/recharts/react-smooth/compare/v4.0.2...v4.0.4
but you're right. when I installed the package, it had the correct peer dependencies.

**Comment by ckifer** [comment]
Yeah sorry I was trying to do it quickly and the tag already existed for whatever reason. Should be good to go installation wise, sorry for the confusion

**Comment by ckifer** [comment]
Closing this up
