### ISSUE TITLE
not working react 16

### ISSUE THREAD

**Issue by theskillwithin** [recharts/react-smooth#19]
react-smooth@0.3.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-smooth@0.3.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by Graham42** [comment]
This is has been fixed by https://github.com/recharts/react-smooth/pull/20
