### ISSUE TITLE
Uncaught Error: Cannot find module "react-transition-group/Transition"

### ISSUE THREAD

**Issue by yuraxdrumz** [recharts/react-smooth#23]
Hey. After switching to react 16 and reinstalling dependencies I came across this error:

ERROR in ./node_modules/react-smooth/lib/AnimateGroupChild.js
Module not found: Error: Can't resolve 'react-transition-group/Transition' in
 '\node_modules\react-smooth\lib'
 @ ./node_modules/react-smooth/lib/AnimateGroupChild.js 21:18-62
 @ ./node_modules/react-smooth/lib/AnimateGroup.js
 @ ./node_modules/react-smooth/lib/index.js
 @ ./node_modules/recharts/es6/polar/RadialBar.js
 @ ./node_modules/recharts/es6/index.js
 @ ./src/components/Dashboard/Main/index.js
 @ ./src/components/Dashboard/index.js
 @ ./src/components/App/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:5000 webpack/hot/dev-server babel-polyfill react react-dom ./src/index.js

I dug into the lib folder and saw you are trying to import from react-transition-group/Transition but when I changed it to import { Transition } from react-transition-group it started working. 
Can you please investigate?

**Comment by GiancarlosIO** [comment]
same here :cry:
