### ISSUE TITLE
Support react-transition-group 4.x

### ISSUE THREAD

**Issue by sevdog** [recharts/react-smooth#33]
`react-transition-group` has evolved since version `2.5` (the one marked in `package.json`).

If someone with this library (or using recharts which requires this) is willing to use any new feature of RTG he will need two different versione of RTG.

Version `4.0.1` of RTG was released last year.

**Comment by ckifer** [comment]
Agreed. Created a PR for 2.0.2 https://github.com/recharts/react-smooth/pull/72

But we can't upgrade `react-transition-group` without dropping support for react <16.6.

That is safe to do, but we'll have to wait for a recharts major release

**Comment by ckifer** [comment]
this is merged/released so closing
