### ISSUE TITLE
Avoid importing all of Lodash for only 2 functions

### ISSUE THREAD

**Issue by wopian** [recharts/react-smooth#34]
Currently the following files import the entire Lodash package:

- https://github.com/recharts/react-smooth/blob/8a771ed822a72e2f26fd84b08c1cba89216d16ee/src/Animate.js
- https://github.com/recharts/react-smooth/blob/af83bfc4a75e3c1ce1465ac0619002d8e8a19314/src/AnimateGroupChild.js

These could be refactored to the following respectively:
- `import isEqual from 'lodash/isEqual';`
- `import isNumber from 'lodash/isNumber';`

This would vastly cut down the bundle size of `react-smooth` in production. https://bundlephobia.com/result?p=react-smooth@1.0.5

**Comment by priscillamac** [comment]
Had a look into this and even after the refactoring, size didn't change. It seems that it's already being treeshaken by webpack.

**Comment by semoal** [comment]
I've did several changes on my branch and passed from `58.2KB` to `32.8 KiB`, a 55.8242% of difference.
Probably this are good news... :)

**Comment by semoal** [comment]
Released on 2.0.0, we can close this issue.
![Screenshot 2021-03-23 at 16 07 28](https://user-images.githubusercontent.com/22656541/112168798-e6c54800-8bf1-11eb-966c-70686e38c477.png)
