### ISSUE TITLE
Update to react v17 support

### ISSUE THREAD

**Issue by Himadu2000** [recharts/react-smooth#45]
This library currently doesn't have react v17 as a peer-dependency,

Therefore,
`react-smooth@1.0.6" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".`
`react-smooth@1.0.6" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".`

So updating this is appreciated.

**Comment by mhuggins** [comment]
+1, this happens indirectly as a result of adding `recharts` as a dependency to a project.

**Comment by arcthur** [comment]
2.0.0 supported
