### ISSUE TITLE
Legend shows issue in recharts piechart with responsive container

### ISSUE THREAD

**Issue by adity2** [recharts/react-smooth#51]
I have tried working with responsive container in recharts using piechart and legend but this creates many issues like gettine "negative rect value" this value only becomes negative while you try to align legend to left or right. The piechart is not working responsive when I align Legend to left or right.
<ResponsiveContainer width="100%" height={250}>
        <PieChart >
        <Legend layout="vertical" verticalAlign="top" align="left"/>
            <Pie
                data={dataStore} 
                dataKey="value"
                outerRadius="80%" 
                innerRadius="50%"
                fill="#884d8"
                paddingAngle={0.5}
                >
                {dataStore.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={colors[index % colors.length]} />
                ))}
            </Pie>
        </PieChart>
        </ResponsiveContainer>

**Comment by adity2** [comment]
I have found a trick for this one and that is working for me but please have look into this need a better resolution from your end. 
Trick :
don't use align  in legend let it be default and then handle .recharts-legend-wapper class in scss by making left:0px; in (desktop,ipad).
But if you say it is responsive then it must work with align as well. And the legend alignment should not create issue on piechart, as "<pie>" is a different element.

**Comment by adity2** [comment]
@xile611 please help me out if there's something else we have to use here.

**Comment by ckifer** [comment]
This is not the recharts repository. Please re-create this issue in https://github.com/recharts/recharts
